### ISSUE TITLE
Create plugin base for AesirX Analytics

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/wordpress-analytics-plugin#1]
We need a WordPress plugin to be able to use AesirX Analytics to capture pages visits through the WordPress installation and connect to a 1st party server to report them.

Essentially it needs to use https://github.com/aesirxio/analytics and wrap it up in a WP plugin, so it's an easy-to-install solution.

The plugin needs to be configurable so that it can set the license details, 1st party server etc to be configured from the plugin configuration.

**Comment by thaoredweb** [comment]
it works on WP
![image](https://user-images.githubusercontent.com/30283123/226530936-e068af48-c275-4cd6-8694-c813f7c3c4c0.png)
